name: Uptime CI
on:
  schedule:
    #- cron: "*/5 * * * *"
  repository_dispatch:
    types: [uptime]
  workflow_dispatch:
jobs:
  release:
    name: Check status
    runs-on: ubuntu-latest
    steps:
    - name: glitch
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://citrine-pointy-armchair.glitch.me'
        method: 'POST'
